# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88cb03a118fb3f0178badb4c70d497c22958a99c73d30b430040288659254806cac203c014880912a97377213a3f7369a511c375beaacd8b7effc14c7a7e2cf7

test:
  secret_key_base: ea814b6294b3d0fba18d0c7127c5dd9746ecf3ee1c3472b724feed97d3298df9a506c1343b5c451551cb7d99cf5c792cc4517b05d3fc1e73737b3a25d878a32e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
